=== adebola-io/spry/schemas/item.schema.json
{
   "$schema": "http://json-schema.org/draft-07/schema#",
   "type": "array",
   "items": {
      "type": "object",
      "properties": {
         "id": {
            "type": "string"
         },
         "name": {
            "type": "string"
         },
         "added": {
            "type": "string",
            "format": "date-time"
         },
         "category": {
            "type": "string",
            "enum": [
               "shirts & trousers",
               "shoes",
               "accessories",
               "formal wear",
               "dresses & gowns",
               "jackets & hoodies"
            ]
         },
         "description": {
            "type": "string"
         },
         "images": {
            "type": "string"
         },
         "variants": {
            "type": "array",
            "items": {
               "type": "object",
               "properties": {
                  "name": {
                     "type": "string"
                  },
                  "color": {
                     "type": "array",
                     "items": {
                        "type": "number"
                     }
                  }
               },
               "required": ["name", "color"]
            }
         },
         "sales": {
            "type": "number"
         },
         "quantity": {
            "type": "number"
         },
         "tags": {
            "type": "array",
            "items": {
               "type": "string"
            }
         },
         "reviews": {
            "type": "array",
            "items": {
               "type": "object",
               "properties": {
                  "userId": {
                     "type": "string"
                  },
                  "content": {
                     "type": ["string", "null"]
                  },
                  "rating": {
                     "type": "integer",
                     "enum": [1, 2, 3, 4, 5]
                  },
                  "date": {
                     "type": "string",
                     "format": "date-time"
                  }
               },
               "required": ["userId", "content", "rating", "date"]
            }
         },
         "price": {
            "type": "object",
            "properties": {
               "value": {
                  "type": "number"
               },
               "currency": {
                  "type": "string",
                  "enum": ["USD", "NGN", "CAD"]
               },
               "discount": {
                  "type": ["object", "null"],
                  "properties": {
                     "name": {
                        "type": "string"
                     },
                     "percent": {
                        "type": "number"
                     }
                  },
                  "required": ["name", "percent"]
               }
            },
            "required": ["value", "currency", "discount"]
         }
      },
      "required": [
         "id",
         "name",
         "added",
         "category",
         "description",
         "images",
         "variants",
         "sales",
         "quantity",
         "tags",
         "reviews",
         "price"
      ]
   }
}

=== adebola-io/spry/data/testing/items/womens_jackets.json
[
   {
      "id": "10",
      "name": "Women's Lightweight Waterproof Long Softshell Tactical Jacket Fleece Lined Windbreaker",
      "added": "2023-01-10T09:00:00.000Z",
      "category": "jackets & hoodies",
      "images": "0000K",
      "quantity": 30,
      "sales": 120,
      "description": "⭐Lightweight&Feminine Cut: Slim fit has a modern cut.Falls at midthigh.with a pull cord if you'd like to taper around your waist area and have a bit of a shape show.The drawstring creates waist and flattering shape.This lightweight insulated fall jacket keeps garments packable&easy to stuff in backpacks and luggage (Tips:Women's jackets are loose fit, please refer to the last size chart before purchasing)\n⭐Windproof Warm Jacket: The tight weave and water-repellent durable fabric.Lined with polar fleece to be extra soft and skin-friendly.The length keep me plenty warm and comfortable.Blocks the wind and isn't too warm while being active.This softshell long jacket with reflective strip detachable hood(keep you well protected in rainy and windy day）\n⭐All-weather Waterproof Jacket: DWR(Durable Water Resistant) treated softshell exterior offers windproof performance while maintaining breathable comfort and repels light rain,moisture and snowflake.Ladies softshell tactical windbreaker features our durable water and wind resistant shell to keep the elements out while keeping you dry and warm.With 3000mm/H2O waterproof index.Built-in high permeability film contribute significantly to waterproof\n⭐Practical Features: Hideaway drawcord adjustable waist offer a better fit and fashion stylish.Zip-through cadet collar with chin guard.Loop&hook adjustable cuffs.5 Pockets design-1 chest zippered pocket.2 large zipped front pockets and 2(one on each side) huge (2.7in x 10in) inside pockets where you can keep valuables dry.Allows you to exercise freely without worrying about items falling\n⭐Occasion: The transition from Winter/Spring and Fall/Winter jacket.This casual lightweight warm fleece lined jacket is the great choice for casual daily work wear,military army outdoor, outdoor sports, snowboarding,skiing,mountaineering,skating,traveling,camping,hiking,cycling,climbing,fishing,riding,hunting, travelling and adventure.This stylish and functional Outwear should accompany you when you are out adventure and on your daily commute\n",
      "tags": [
         "slim",
         "waterproof",
         "women",
         "drawstring",
         "polar fleece",
         "chin guard"
      ],
      "variants": [
         { "name": "Navy", "color": [65, 75, 63] },
         { "name": "Black", "color": [21, 21, 21] },
         { "name": "Grey", "color": [48, 48, 48] },
         { "name": "Light Grey", "color": [124, 123, 128] },
         { "name": "Purple", "color": [174, 67, 132] },
         { "name": "Red", "color": [234, 43, 82] }
      ],
      "price": { "currency": "USD", "discount": null, "value": 62.76 },
      "reviews": [
         {
            "userId": "12345",
            "content": "Made with precision and to perfection. The magenta color is perfect, lining soft and cuddling. Sturdy on the outside and soft and flexible on the inside. However the 2XX size is more like 1XX. I can barely zip it up.",
            "date": "2023-01-12T08:35:44.000Z",
            "rating": 5
         },
         {
            "userId": "12345",
            "content": "This is a nice lightweight jacket for those days when you need something more than a sweater but not a heavy coat. Plenty of pockets on both the inside and outside of the jacket, which is nice for those of us who commute on foot.\n\nBut the zipper...I wore it for the first time today on a longer walk and after half a mile the zipper had managed to work itself into a weird state where the two sides no longer aligned. I was afraid I was going to have the break the zipper to get out of the jacket, luckily I didn't but I wore it unzipped for the rest of the walk.\n\nOverall it's fine for what I need, I'd suggest maybe going up a size or two to avoid the zipper issue",
            "date": "2023-01-11T12:41:00.000Z",
            "rating": 3
         },
         {
            "userId": "12345",
            "content": "This coat is perfect! Not real warm, but just right for those 40 degree temperatures. I wear a size medium shirt and ordered a large for the jacket and it fits just as I had hoped. The sleeves are a little long but workable! It’s a light fleece inner lining, but it’s perfect for what I needed!",
            "date": "2023-01-10T04:00:23.000Z",
            "rating": 5
         },
         {
            "userId": "12345",
            "content": "Unfortunately I had to return this jacket. I loved the pockets and the look of it but even though I followed their measurement charts it was too tight across the chest and hips for me. While I could get the jacket on, it was definitely snug and would have been uncomfortable to wear while doing much of anything. I was afraid to sit down in it as I didn't want to bust the zipper. Otherwise I really liked the jacket so I gave it 4 stars for the measuring chart inaccuracies.",
            "date": "2023-01-11T06:24:55.000Z",
            "rating": 4
         }
      ]
   },
   {
      "id": "11",
      "name": "Raincoat Women Waterproof Long Hooded Trench Coats Lined Windbreaker Travel Jacket S-XXL",
      "added": "2023-01-05T09:00:00.000Z",
      "category": "jackets & hoodies",
      "images": "0000L",
      "quantity": 51,
      "sales": 199,
      "description": "Material:98% Polyester, 2% Spandex,100% Waterproof material with striped cotton lined, Breathable, Soft touch,Windproof, Easy to package\nDesign:This Women Rain Jacket with attached hood, drawstring waist design.solid pattern,Sun Protection and Waterproof Function,Breathable, Skin-touch, Quick-drying, Lightweight casual fit, front pocket decoration, Suitable for all seasons.\nOccasion:Suitable for your hiking,climbing,traveling,camping,sport outdoor,easy to quick-drying when it is light rain or snow and wind.\nSize:Please check our SIZE CHART image in the Left or detailed size info below in product description carefully.If you have any question about size,just contact to us,we'll try our best to help you get a wonderful shopping experience\nGarment Care: We recommend you Washing by Hand or machine wash, Dry Clean, Do not iron, to Protect waterproof material performance\n",
      "tags": [
         "long",
         "polyester",
         "spandex",
         "trench coat",
         "hood",
         "waterproof",
         "women",
         "drawstring",
         "polar fleece",
         "chin guard"
      ],
      "variants": [
         { "name": "Army Green", "color": [88, 89, 65] },
         { "name": "Black", "color": [21, 21, 21] },
         { "name": "Gray", "color": [48, 48, 48] },
         { "name": "Pink", "color": [223, 182, 168] },
         { "name": "Purple", "color": [84, 56, 114] },
         { "name": "Wine Red", "color": [131, 33, 41] }
      ],
      "price": {
         "currency": "USD",
         "discount": { "name": "Sale", "percent": 15 },
         "value": 54.99
      },
      "reviews": [
         {
            "userId": "12345",
            "content": "I ordered an XL. Reviews I looked at before were kind of all over the place. Jacket didn't come with weird smell. It's light, but warm. Has a draw string around the waist to help shape. Has buttons and a zipper. Im able to zip with ease, not to tight in any given place. It fits me perfectly, but I definitely won't be able to throw it over a hoody, as some people were mentioning. I have wide shoulders and it fits comfortably, but there is no extra room there. The rest is pretty spacey in a good way. So if you want to wear a hoody under this jacket, size up. I'm used to a cool, wet climate, so a lighter waterproof, fleece lined jacket works perfect for me. I needed something for daily errands and running the kids to and from school and this jacket hit every need for me. 10/10 recommend. It's my new favorite jacket.",
            "date": "2023-01-11T05:49:43.000Z",
            "rating": 5
         },
         {
            "userId": "12345",
            "content": "I bought this raincoat because I am so tired of wearing black all the time and needed some color in my life. It is a nice raincoat, it has a lot of wrinkles and I don’t know how to get them out because you can’t put it in the dryer and you obviously can’t iron it, so I’m hoping that as it hangs in my closet, the wrinkles will eventually fall out. I haven’t worn it yet because it’s too cold, but as soon as we get one of those warmer January days with rain I’m gonna give it a shot. It’s so cute I may end up getting it in another color.",
            "date": "2023-01-11T12:41:00.000Z",
            "rating": 5
         },
         {
            "userId": "12345",
            "content": "Was skeptical when I took it out of the package, and it had a chemical smell and was wrinkled. So I almost returned it. However, I put it in the dryer on low with a bounce sheet, wore it and the smell/wrinkles no longer a problem. I like the lining - adds some style. I am small/petite and have to roll up the sleeves, so the print lining looks good. I also like the tie in order to pull in the waist, yet there is room enough for me to wear a sweater or something underneath. Let's see how it holds up after wearing a bit.",
            "date": "2023-01-10T04:00:23.000Z",
            "rating": 4
         },
         {
            "userId": "12345",
            "content": "Perfect for walking the dog on cool drizzly spring days. Lining is lightweight. I usually have a hard time finding jackets that fit my boobs as Im a 38DD and 225 lbs. the large was perfect! Highly recommend.",
            "date": "2023-01-11T06:24:55.000Z",
            "rating": 5
         }
      ]
   },
   {
      "id": "12",
